[mcp_servers.figma-dev-mode-mcp-server]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.my-mcp-server]
command = "node"
args = ["my-mcp-server.mjs"]
cwd = "/Users/shunwuyu/workspace/lesson/ai_lesson/guang/04/tool-test"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-5061c48d-52b0-4e18-8a91-090f82d50724"]
startup_timeout_ms = 20_000