// app/layout.js
import './global.css'
import { Inter } from 'next/font/google' // 引入字体
// latin 拉丁文 
const inter = Inter({ subsets: ['latin'] }) // 设置字体

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={inter.className}>
            <h1>layout</h1>
            {children}
        </body>
      </html>
    )
  }
  