import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav
          style={{
            display: "flex",
            gap: 16,
            padding: "12px 24px",
            borderBottom: "1px solid #eee",
          }}
        >
          <Link href="/" style={{ textDecoration: "none", color: "#333" }}>
            首页
          </Link>
          <Link href="/about" style={{ textDecoration: "none", color: "#333" }}>
            关于
          </Link>
          <Link href="/articles" style={{ textDecoration: "none", color: "#333" }}>
            文章列表
          </Link>
        </nav>
        <main style={{ flex: 1 }}>{children}</main>
      </body>
    </html>
  );
}
