FROM node:22-alpine AS builder
WORKDIR /app/api
COPY todos-api/package*.json ./
RUN npm config set registry https://registry.npmmirror.com && npm install
COPY todos-api/ .
RUN npm run build

FROM node:22-alpine
WORKDIR /app/api
COPY --from=builder /app/api/dist ./dist
COPY --from=builder /app/api/node_modules ./node_modules
COPY --from=builder /app/api/package.json ./
EXPOSE 3000
CMD ["node", "dist/main"]