// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ?? 兜底：DATABASE_URL 未配置时给空串，避免 TS 报 undefined
    url: process.env["DATABASE_URL"] ?? "",
  },
});
